groups:
  - name: linux_server_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Penggunaan CPU Sangat Tinggi pada {{ $labels.instance }}"
          description: "Kapasitas CPU terpakai melampaui 85% selama lebih dari 5 menit berturut-turut."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Sisa Memori RAM Server Kritis"
          description: "Penggunaan RAM saat ini mencapai {{ $value | printf \"%.2f\" }}% pada instance {{ $labels.instance }}."
